### ISSUE TITLE
Consisting to Staff affects Voice numbering

### ISSUE THREAD

**Issue by uliska** [openlilylib/edition-engraver#1]
When the edition-engraver is consisted to `Voice` *and* `Staff` the voices are counted differently.

In `example-1.ly` there are colored notes in `Voice.A`. When the edition-engraver is consisted to both Voice and Staff, this affects the upper voice, but when Staff is omitted the notes in the lower voice are colored.

It seems that "counting" voices somehow includes the Staff, and omitting the Staff will shift the voice to one below.

Consequently, when I change `Voice.A` to `Voice.B` *with* Staff the lower voice is colored while *without* Staff nothing happens at all because the engraver tries to address the *third* voice that doesn't exist.

I didn't check how this behaves when more than one Staff is present or when the Staff is nested in a PianoStaff etc.

**Comment by jpvoigt** [comment]
If you omit the EE in Staff, the voices still receive the editionID. There is a wildcard, that refers to the parent ID. And the first time the wildcard is expanded twice ...

example-1.edition.log:
(sing with bach along along Voice A) ""
(sing with bach along Voice A) ""
(sing with bach Score A) ""

I will look into it.

**Comment by jpvoigt** [comment]
should be solved with commit 3a069703ab19d59aff37877a9ab628ceb35f3b91
