### ISSUE TITLE
point-and-click links possible?

### ISSUE THREAD

**Issue by uliska** [openlilylib/edition-engraver#10]
Is it possible to add point-and-click links to items (e.g. markup, rehearsal marks etc.) that are inserted through the `edition-engraver`?

**Comment by jpvoigt** [comment]
It *should* be possible. I'll try it.
The link would then point to the editionMod entry - this is the location object available.

**Comment by uliska** [comment]
Yes, that's where it should point to.

**Comment by jpvoigt** [comment]
This implemented. It points to the Event given to the EE.

**Comment by uliska** [comment]
Sounds great, I'll have to test ASAP :+1:
