### ISSUE TITLE
Recent merge breaks edition-engraver

### ISSUE THREAD

**Issue by markk** [openlilylib/edition-engraver#27]
Hi Jan-Peter,

After this recent merge 305728825ee9d2ac00cea675c34c9fbaaeaf07ac edition-engraver is broken here. There is still console output, but all of the usage examples compile with the mods taking no effect. 

Everything seems to work fine with if I checkout aaf23257fcc0305eca31c3eb271193ff5282dfbd

Thanks,

Mark

**Comment by jpvoigt** [comment]
Hi Mark,

o dear, yes thats true.
There is a change that I introduced some time ago in another branch. I
suspect a some commits earlier ...

For now I push a short workaround.

Jan-Peter

Am 29.10.18 um 17:32 schrieb markk:

**Comment by markk** [comment]
Thanks! As an aside, I don't suppose support for \ottava might be possible?
